[package]
name = "rusty_mvc"
version = "0.1.0"
authors = ["Navrin <navman360@gmail.com>"]

[dependencies]
regex="0.2.2"

[lib]
name = "rusty_mvc"
path = "src/lib.rs"

# [[bin]]
# name = "rusty_mvc_test"
# path = "src/bin.rs"